name: Update sloka-index
on:
  push:
    branches:
      - main
jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Update sloka-index.json
        run: |
          # Add your logic to update sloka-index.json
          git add sloka-index.json
          git diff --staged --quiet || git commit -m "chore: auto-generate sloka-index.json [skip ci]"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/moulibheemaneti/sloka-directory.git HEAD:main
