name: Generate sloka-index.json on Main Update

on:
  push:
    branches:
      - main

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # You can change this if needed

      - name: Run the index generation script
        run: node scripts/indexer.js
        # Update the path if your script is elsewhere

      - name: Commit and push sloka-index.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sloka-index.json
          git diff --staged --quiet || git commit -m "chore: auto-generate sloka-index.json [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
